MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
DATASETS:
  SOURCE_TRAIN: "gta5_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.2
#   PIXEL_MEAN: [103.939, 116.779, 123.68]
#   PIXEL_STD: [1., 1., 1.]
#   TO_BGR255: True
SOLVER:
  BASE_LR: 2.5e-4
  BASE_LR_D: 0.0001
  MAX_ITER: 62500
  STOP_ITER: 40000
  BATCH_SIZE: 4
