MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  NUM_CLASSES: 6
DATASETS:
  SOURCE_TRAIN: "PotsdamRGB_train"
  TARGET_TRAIN: "Vaihingen_train"
  TEST: "Vaihingen_train"
INPUT:
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.2
  SOURCE_INPUT_SIZE_TRAIN: (512, 512)
  TARGET_INPUT_SIZE_TRAIN: (512, 512)
#  SOURCE_PIXEL_MEAN: [ 0.471, 0.319, 0.316 ] # V_IRRG
#  SOURCE_PIXEL_STD: [ 0.206, 0.140, 0.136 ] # V_IRRG
#  SOURCE_PIXEL_MEAN: [ 0.384, 0.364, 0.338 ] # P_IRGB
#  SOURCE_PIXEL_STD: [ 0.117, 0.117, 0.121 ] # P_IRGB
  SOURCE_PIXEL_MEAN: [0.340, 0.364, 0.338] # P_RGB
  SOURCE_PIXEL_STD: [0.118, 0.117, 0.121] # P_RGB
#  TARGET_PIXEL_MEAN: [ 0.384, 0.364, 0.338 ] # P_IRGB
#  TARGET_PIXEL_STD: [ 0.117, 0.117, 0.121 ] # P_IRGB
#  TARGET_PIXEL_MEAN: [0.340, 0.364, 0.338] # P_RGB
#  TARGET_PIXEL_STD: [0.118, 0.117, 0.121] # P_RGB
  TARGET_PIXEL_MEAN: [0.471, 0.319, 0.316] # V_IRRG
  TARGET_PIXEL_STD: [0.206, 0.140, 0.136] # V_IRRG
  TEST_PIXEL_MEAN: [0.471, 0.319, 0.316] # V_IRRG
  TEST_PIXEL_STD: [0.206, 0.140, 0.136] # V_IRRG
#  TEST_PIXEL_MEAN: [ 0.340, 0.364, 0.338 ] # P_RGB
#  TEST_PIXEL_STD: [ 0.118, 0.117, 0.121 ] # P_RGB
#  TEST_PIXEL_MEAN: [ 0.384, 0.364, 0.338 ] # P_IRGB
#  TEST_PIXEL_STD: [ 0.117, 0.117, 0.121 ] # P_IRGB
  INPUT_SCALES_TRAIN: (1.0, 1.0)
#   TO_BGR255: True
SOLVER:
  BASE_LR: 2.5e-4
  BASE_LR_D: 0.0001
  MAX_ITER: 102500
  STOP_ITER: 80000
  BATCH_SIZE: 8
