MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: False
  NUM_CLASSES: 6
DATASETS:
  SOURCE_TRAIN: "Vaihingen_self_distill_train"
  TEST: "Vaihingen_test"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (512, 512)
  INPUT_SIZE_TEST: (512, 512)
  INPUT_SCALES_TRAIN: (0.5, 1.5)
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.2
  SOURCE_PIXEL_MEAN: [ 0.471, 0.319, 0.316 ]
  SOURCE_PIXEL_STD: [ 0.206, 0.140, 0.136 ]
SOLVER:
  BASE_LR: 5e-4
  MAX_ITER: 61250
  STOP_ITER: 40000
  BATCH_SIZE: 5
