MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth'
  FREEZE_BN: True
  NUM_CLASSES: 6
DATASETS:
  SOURCE_TRAIN: "Vaihingen_train"
  TEST: "Vaihingen_test"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (512, 512)
  INPUT_SIZE_TEST: (512, 512)

#  SOURCE_PIXEL_MEAN: [0.384, 0.364, 0.338] #IRGB
#  SOURCE_PIXEL_STD: [0.117, 0.117, 0.121] #IRGB
#  SOURCE_PIXEL_MEAN: [0.340, 0.364, 0.338] #RGB
#  SOURCE_PIXEL_STD: [0.118, 0.117, 0.121] #RGB
  SOURCE_PIXEL_MEAN: [ 0.471, 0.319, 0.316 ] # V_IRRG
  SOURCE_PIXEL_STD: [ 0.206, 0.140, 0.136 ] # V_IRRG
  TEST_PIXEL_MEAN: [0.471, 0.319, 0.316] # V_IRRG
  TEST_PIXEL_STD: [0.206, 0.140, 0.136] # V_IRRG
  INPUT_SCALES_TRAIN: (1.0, 1.0)
SOLVER:
  BASE_LR: 5e-4
  MAX_ITER: 41250
  STOP_ITER: 30000
  BATCH_SIZE: 8
