MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: False
  NUM_CLASSES: 2
DATASETS:
  SOURCE_TRAIN: "WC_GES_self_distill_train"
  TEST: "WC_GES_test"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (650, 650)
  TARGET_INPUT_SIZE_TRAIN: (650, 650)
#  INPUT_SCALES_TRAIN: (0.5, 1.5)
#  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  BRIGHTNESS: 0.2
  CONTRAST: 0.2
  SATURATION: 0.2
  HUE: 0.1
  SOURCE_PIXEL_MEAN: [ 76.0735, 77.3002, 77.2338 ] # WC_GES
  SOURCE_PIXEL_STD: [ 40.2527, 36.6712, 33.8240 ]  # WC_GES
  INPUT_SCALES_TRAIN: (0.0, 0.0)
SOLVER:
  BASE_LR: 5e-4
  MAX_ITER: 61250
  STOP_ITER: 50000
  BATCH_SIZE: 2
